name: "Install AWS Cli and Assumes a role"
description: "Installs the AWS CLI"
author: "Martyn Crow <martyn.crow@vodafone.com>"

inputs:
  aws-access-key-id:
    required: false
    description: "AWS Access Key ID"
  aws-secret-access-key:
    required: false
    description: "AWS Secret Access Key"
  role-to-assume:
    description: ""
    required: true
  role-session-name:
    description: ""
    required: false
    default: "GitHub_to_AWS_via_FederatedOIDC"
  aws-region:
    required: false
    description: "AWS Region"
    default: "eu-west-1"

outputs:
  aws-access-key-id:
    description: "AWS Access Key ID"
    value: ${{ steps.creds.outputs.aws-access-key-id }}
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    value: ${{ steps.creds.outputs.aws-secret-access-key }}
  aws-session-token:
    description: "AWS Session Token"
    value: ${{ steps.creds.outputs.aws-session-token }}

runs:
  using: composite
  steps:
    - name: Install AWS CLI
      shell: bash
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q -o awscliv2.zip
        sudo ./aws/install --update 
        aws --version

    - name: configure aws credentials
      id: creds
      if: ${{ inputs.role-to-assume }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ inputs.role-session-name }}
        aws-region: ${{ inputs.aws-region }}
        output-credentials: true

    - name: Configure AWS Credentials
      if: ${{ inputs.aws-access-key-id != '' && inputs.aws-secret-access-key != '' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

